sudo: false
language: node_js
node_js:
- 0.12
- 4
- node
install:
- npm install
script:
- npm run test:ci
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: thibaudcolas@gmail.com
  api_key:
    secure: FqIT5LeQ/SKzfolFY8u6Vv8nYI47gIV3KHSv1beydBsyHfYpJ4bOmgcV5SwgO7ovhSJzO+X25YBofx2LLlAgACXkgAZ9Wdl4kGSzGqrAXdGQ5/r9+EhNMi0xXrodi4YXSGtbk0QPmOyMDhaT4vm5Y9jKyW1R5OtZcG4vVYy1h6KrH3qAkpnicDlN7NfrinV8lklQWaImY6B1id+KFU5868RIY5YotIXNgzpZAuYQur2up68gutAiArH6PfDy2036wgK0sZcUf0A8x28/TJMSkb1K+WbSUiikMA6t9v2QxHh4OYzpJrnffRSo5+sN/3feei/5Ztx2aEghekyF2oJQwP4gsEn75dNpPJjt7AOqDARTFeTSLlJQaLdhiHhTs8Ds0sagVByNmVrZakyR1TDOvqIZG8JqXQmOSSSGzy1fBhXyHBTCzrVsLKV/af+TocYwu3H3EnHkSxix31ZWcBbmRAbg7c+AahCYacaUxKKhCRuyJT6L8YkjEiXvQEYNv64S/5K1gy3K1FUYqhhfsM2oFQQMGTfASu4uHA9WsA436SgKIiCaHDtmkUSwtovNrsK+LI24mGlycDsHMxF4wVndmqkI5BXeUxBfBk8ncYmgD91aM+MzZvvgI+n/JhyeD4tQ7Q/bRFoVdfw8EDCg3YcBqxZ0/Qwlbt1yqLYnmqQitm4=
  on:
    tags: true
    repo: thibaudcolas/testdrived3
  skip_cleanup: true
